### ISSUE TITLE
Kraplow AI

### ISSUE THREAD

**Issue by alwinm** [ccarrster/kraplow#61]
Hi Chris!

I love your Kraplow game. However, I noticed quirky behaviors in the AI that could probably be fixed. I myself have no knowledge of the code behind it all (I am very impressed, by the way, with your translation of Bang into computer code), but I felt like I might give you a few ideas that came to me. 

Some of these quirky behaviors aren't necessarily bad, but just obviously not smart. -For example, in Bang!, there are cards which are clearly better than others. I much prefer Mustangs, Barrels, Scopes, and Wells Fargo to a simple bang or Missed! However, the AI does not seem to share this enthusiasm, and during a General Store selection process, the AI will often choose lower valued cards over higher valued cards. 
-The Sheriff kills its deputies rather than deciding to kill players which are currently targetting him. Although it cannot be known who the deputies are and are not, a player should at least prefer to attack someone attacking him/her/it rather than someone who poses no threat. 
-I have not been paying attention, but I sure hope the deputies have the common sense not to hit the Sheriff. 
-Guns. When an AI has several gun cards, it will randomly play all of them. Sometimes it will replace a good gun with a gun with less range. 
-Frozen. When there are two or even three AI remaining, it is sometimes the case that they will not kill each other, often discarding bangs. To remedy this, I would suggest that each AI keeps track of knowledge. Since it is public knowledge the total number of Sheriffs, Deputies, Outlaws, and the 1 renegade, when an AI witnesses the death of a number of them, it should be able to tell who the last 2 players standing are, and should know that it needs to be killing whoever remains at the end. 

I was thinking that a good way to do the AI is to make a few different AI strategies, and then over a period of time, test them. Say there are 3 strategies, A, B, and C, and whenever an AI game is created, each AI randomly selects one of the 3. After a few thousand games, whichever AI has the highest success rate given a character and role will be selected as the best one. For example, the AI which wins most often as Slab the Killer as a renegade will eventually be the only AI strategy that is chosen for future AI Slab the Killer Renegades.

Here, I propose a strategy (A):
As the Sheriff: First turn, I play whatever I can but I do not bang anyone. Indians and Gatlings are fine. I save my bangs until I see who is an outlaw. Then, I only target anyone who is targetting me, and no one else. 
As the Deputy: If I feel aggressive, I will start banging immediately. Otherwise, I will wait for an outlaw to target the Sheriff. Otherwise, I will attempt to close the distance between myself and the Sheriff immediately to act as his meatshield and increase distance by 1. 
As the Outlaw: Target sheriff immediately. Otherwise (if out of range), kill whoever is furthest from the sheriff and nearest to myself because they are more likely able to target myself than the sheriff. Getting the Sheriff in range is a priority, so Volcanic is only okay when paired with Scope (if sheriff is within distance 2) or without scope when sheriff is within distance 1. 
As the renegade: Stay out of trouble. Indians and gatlings and beers are my friend. 

Anyway, that's just an idea for target selection for AI that makes more sense than random firing.

**Comment by ccarrster** [comment]
Fixed the bug with the last two players. There was an index issue in an array of strings.

**Comment by enkessler** [comment]
The AI still doesn't wait to know who anyone is before trying to kill them. I just had a round one deputy death because the crazy sheriff Willy The Kid decided to unload their hand on the person next to them and then lost the rest of their hand when that person turned out to be a deputy.

**Comment by ccarrster** [comment]
This is true. Bag of door knobs for who to target.
